language: node_js

node_js:
  - "8"

cache:
  directories:
    - $HOME/.npm

before_install:
  - export TZ='Asia/Shanghai'
  - sudo apt-get install calibre fonts-noto-cjk -y

install:
  - npm install gitbook-cli -g
  - gitbook install

script:
  - gitbook build . ./build
  - xvfb-run gitbook pdf ./ ./2019-China-Open-Source-Report.pdf
  - gitbook epub ./ ./2019-China-Open-Source-Report.epub
  - gitbook mobi ./ ./2019-China-Open-Source-Report.mobi

deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: build
    on:
      branch: master

  - provider: releases
    api_key: $GITHUB_TOKEN
    file:  
      - "2019-China-Open-Source-Report.epub"
      - "2019-China-Open-Source-Report.pdf"
      - "2019-China-Open-Source-Report.mobi"
    skip_cleanup: true
    on:
      tags: true